In [11]:
#E21CSEU0697
#DSV Virupaksha vegi
import numpy as np

In [12]:
# Create matrix of size 10*10 with random integer numbers
A = np.random.randint(10, size=(10, 10))
print(A)

[[9 6 5 2 4 3 7 2 6 8]
 [0 2 4 3 1 7 2 6 7 9]
 [4 5 7 0 3 2 5 6 7 3]
 [3 3 8 0 0 8 1 8 4 6]
 [7 4 4 8 8 5 3 7 2 1]
 [7 7 0 1 2 8 0 6 3 3]
 [4 3 6 8 4 1 1 1 1 6]
 [6 5 5 4 4 4 3 9 7 9]
 [9 9 0 2 5 2 9 5 2 2]
 [4 5 9 7 1 1 6 5 5 5]]


In [13]:
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.16395343 -0.15312899 -0.13963004  0.01687013  0.06536578  0.03532788
  -0.15044644  0.10184433 -0.11364235  0.08524355]
 [-0.1601809   0.04570777  0.17220622 -0.05106615 -0.14288549  0.11254781
   0.20955181 -0.08537055  0.10966002 -0.04863968]
 [-0.00279533 -0.04491571  0.07731313  0.07959744 -0.00810119 -0.02647814
   0.07160177 -0.06031515 -0.01886767 -0.00888468]
 [-0.00313065  0.02908548 -0.08227783 -0.07532633  0.0491249   0.04275194
  -0.03456323 -0.00421362 -0.04328756  0.12331274]
 [-0.04837411  0.05590076  0.15719264 -0.01048379  0.03327856 -0.06936529
   0.14892707 -0.03833597  0.05996903 -0.20368971]
 [ 0.04707291  0.09247855 -0.02879735  0.04249507  0.0588717   0.03384868
  -0.02543319 -0.1466224  -0.00688906 -0.01038151]
 [ 0.04527827  0.06472296 -0.07229338  0.04151857  0.03698815 -0.10521708
  -0.08602117 -0.06255954  0.08776598  0.04106601]
 [-0.08539636 -0.05250291 -0.05318342  0.05504152  0.01174311 -0.05034185
  -0.06669164  0.14909156  0.04222967  0.01962943]


In [14]:
#Calculate dot product of the matrix with same matrix in transpose A.AT
print(np.dot(A,A.transpose()))

[[324 203 232 204 225 193 182 298 266 254]
 [203 249 177 226 162 159 134 264 123 197]
 [232 177 222 198 184 151 123 249 195 219]
 [204 226 198 263 178 184 126 262 139 203]
 [225 162 184 178 297 192 183 261 233 221]
 [193 159 151 184 192 221 100 223 196 140]
 [182 134 123 126 183 100 181 194 129 192]
 [298 264 249 262 261 223 194 354 239 273]
 [266 123 195 139 233 196 129 239 309 201]
 [254 197 219 203 221 140 192 273 201 284]]


In [15]:
#Decompose the original matrix using eigen decomposition print the eigen values and eigen vectors
val, vec = np.linalg.eig(A)
# eigenvectors
print("eigenvectors\n")
print(vec)
#eigenvalues
print("\neigenvalues\n")
print(val)

eigenvectors

[[ 0.35876389+0.j          0.23443282-0.18047087j  0.23443282+0.18047087j
  -0.15077308-0.22934404j -0.15077308+0.22934404j -0.65094567+0.j
  -0.65094567-0.j          0.17036022+0.j          0.0988491 -0.0328276j
   0.0988491 +0.0328276j ]
 [ 0.28508161+0.j         -0.02338965+0.06031566j -0.02338965-0.06031566j
   0.01377622+0.25891675j  0.01377622-0.25891675j  0.4730715 -0.07653119j
   0.4730715 +0.07653119j  0.6677482 +0.j         -0.16976012-0.32885363j
  -0.16976012+0.32885363j]
 [ 0.29475521+0.j          0.00167296-0.35281156j  0.00167296+0.35281156j
   0.03653075-0.21578698j  0.03653075+0.21578698j -0.07849843-0.10618545j
  -0.07849843+0.10618545j  0.1033186 +0.j         -0.07957113-0.08245592j
  -0.07957113+0.08245592j]
 [ 0.29001432+0.j         -0.42156887-0.07404266j -0.42156887+0.07404266j
  -0.0420919 +0.14205251j -0.0420919 -0.14205251j  0.10716659+0.07313214j
   0.10716659-0.07313214j  0.16398111+0.j          0.32048904-0.04325803j
   0.32048904+0.04325803j]

In [17]:
#Calculate jacobian matrix
import autograd.numpy as np
from autograd import grad, jacobian


def cost(A):
    return A[0]**2 / A[1] - np.log(A[1])

jacobian_cost = jacobian(cost)
jacobian_cost(A)

/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in true_divide
  return f_raw(*args, **kwargs)
/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: divide by zero encountered in true_divide
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:52: RuntimeWarning: divide by zero encountered in true_divide
  defvjp(anp.true_divide, lambda ans, x, y : unbroadcast_f(x, lambda g: g / y),
/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:53: RuntimeWarning: divide by zero encountered in true_divide
  lambda ans, x, y : unbroadcast_f(y, lambda g: - g * x / y**2))
/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: inv

array([[[-9223372036854775808,                    0,
                            0,                    0,
                            0,                    0,
                            0,                    0,
                            0,                    0],
        [-9223372036854775808,                    0,
                            0,                    0,
                            0,                    0,
                            0,                    0,
                            0,                    0],
        [                   0,                    0,
                            0,                    0,
                            0,                    0,
                            0,                    0,
                            0,                    0],
        [                   0,                    0,
                            0,                    0,
                            0,                    0,
                            0,             

In [36]:
#Calculate hessian matrix
def hessian(x):
    x_grad = np.gradient(x) 
    hessian = np.empty((x.ndim, x.ndim) + x.shape, dtype=x.dtype) 
    for k, grad_k in enumerate(x_grad):
        # iterate over dimensions
        # apply gradient again to every component of the first derivative.
        tmp_grad = np.gradient(grad_k) 
        for l, grad_kl in enumerate(tmp_grad):
            hessian[k, l, :, :] = grad_kl
    return hessian

hessian(A)

array([[[[  3,  -1,   4,   1,   3,   4,  -3,   0,   1,  -2],
         [  1,   0,   2,  -1,   1,   1,   0,   0,   3,  -2],
         [ -2,   0,   0,  -2,  -2,  -2,   1,  -1,   2,   0],
         [ -3,   0,   1,   1,   1,   0,   0,   0,  -3,   2],
         [  1,   2,   1,   0,   3,   3,   0,   3,  -1,   0],
         [  2,  -1,  -1,   0,  -1,  -1,  -1,   1,   3,  -2],
         [  0,  -2,  -1,   0,  -1,  -3,  -2,  -2,  -1,  -1],
         [ -2,   0,   0,   1,   0,  -1,   1,  -2,  -2,   0],
         [ -3,   2,   0,   2,   1,   0,   1,  -3,   3,  -3],
         [ -3,   4,  -1,   3,   1,   2,   0,  -3,   6,  -5]],

        [[  0,  -2,   1,   1,  -2,   1,   1,  -1,   1,   5],
         [ -4,  -1,   2,   0,   0,  -1,  -1,   0,   0,   2],
         [ -2,  -2,  -1,   0,   1,   0,   0,   1,  -1,  -5],
         [  0,   0,   0,  -1,  -1,   2,   0,   1,   1,  -1],
         [  4,   2,   0,   0,   0,   0,  -1,  -1,   1,   5],
         [  2,   0,  -1,   0,   2,   0,   0,  -1,  -1,   2],
         [ -2,  -1,   

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/diabetes_data_upload.csv")
df.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [4]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
  
df['Gender']= label_encoder.fit_transform(df['Gender'])
df['Polyuria']= label_encoder.fit_transform(df['Polyuria'])
df['Polydipsia']= label_encoder.fit_transform(df['Polydipsia'])
df['sudden weight loss']= label_encoder.fit_transform(df['sudden weight loss'])
df['weakness']= label_encoder.fit_transform(df['weakness'])
df['Polyphagia']= label_encoder.fit_transform(df['Polyphagia'])
df['Genital thrush']= label_encoder.fit_transform(df['Genital thrush'])
df['visual blurring']= label_encoder.fit_transform(df['visual blurring'])
df['Itching']= label_encoder.fit_transform(df['Itching'])
df['Irritability']= label_encoder.fit_transform(df['Irritability'])
df['delayed healing']= label_encoder.fit_transform(df['delayed healing'])
df['partial paresis']= label_encoder.fit_transform(df['partial paresis'])
df['muscle stiffness']= label_encoder.fit_transform(df['muscle stiffness'])
df['Alopecia']= label_encoder.fit_transform(df['Alopecia'])
df['Obesity']= label_encoder.fit_transform(df['Obesity'])

df.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0   40       1         0           1                   0         1   
1   58       1         0           0                   0         1   
2   41       1         1           0                   0         1   
3   45       1         0           0                   1         1   
4   60       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

      class  
0  Positive  
1  Positive  
2  Positive  
3  Positive  
4  Positive

In [5]:
column = 'Age'
df[column] = (df[column] - df[column].min()) / (df[column].max() - df[column].min())
df.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0  0.324324       1         0           1                   0         1   
1  0.567568       1         0           0                   0         1   
2  0.337838       1         1           0                   0         1   
3  0.391892       1         0           0                   1         1   
4  0.594595       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

      class  
0  Positive  
1  Positive  
2  Positive  
3  Positive  
4  Positive

In [7]:
X = df.drop('class',axis= 1)
y = df['class']
print(X)
print(y)

          Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0    0.324324       1         0           1                   0         1   
1    0.567568       1         0           0                   0         1   
2    0.337838       1         1           0                   0         1   
3    0.391892       1         0           0                   1         1   
4    0.594595       1         1           1                   1         1   
..        ...     ...       ...         ...                 ...       ...   
515  0.310811       0         1           1                   1         0   
516  0.432432       0         1           1                   1         1   
517  0.567568       0         1           1                   1         1   
518  0.216216       0         0           0                   0         1   
519  0.351351       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \


In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [9]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [10]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.9375